version: "3"
services:
  api:
    build: ./api
    ports:
      - '${API_PORT}:9000'
    depends_on:
      - db
    container_name: easyPoll-api
  client:
    build: ./client
    ports:
      - '${CLIENT_PORT}:80'
    container_name: easyPoll-client
  db:
    image: mongo
    ports:
      - "${DB_PORT}:27017"
    container_name: easyPoll-db